# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# TODO: Create test user

# Levels

#    t.integer  ""]
levels = Level.create([
    {number: 1, openingdate: Time.now, closingdate: Time.now + 1},
    {number: 2, openingdate: Time.now, closingdate: Time.now + 1},
    {number: 3, openingdate: Time.now, closingdate: Time.now + 1},
    {number: 4, openingdate: Time.now, closingdate: Time.now + 1},
    {number: 5, openingdate: Time.now, closingdate: Time.now + 1},
    {number: 6, openingdate: Time.now, closingdate: Time.now + 1},
    ])


questionslevel1 = Question.create([
  { word: 'selfie', ans1: 'geschilderd landschap', ans2: 'geschilderd zelfportret', ans3: 'gefotografeerd landschap', ans4: 'gefotografeerd zelfportret', hintsemantic: 'otofoto',
    hintsentence: 'Omdat er niemand in de buurt was, maakte de toerist een selfie.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'schaars', ans1: 'in grote hoeveelheden beschikbaar', ans2: 'in kleine hoeveelheden beschikbaar', ans3: 'in stukken geknipt', ans4: 'tweepotig', hintsemantic: 'beperkt',
    hintsentence: 'Positionele goederen worden schaars door de toenemende vraag.', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'hoofdgedachte', ans1: 'in een woord waar tekst over gaat', ans2: 'plotselinge ingeving', ans3: 'omschrijving van tekst in 1 zin', ans4: 'briljant idee', hintsemantic: 'bondig',
    hintsentence: 'Hij zocht naar de hoofdgedachte van de tekst.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'ontkenning', ans1: 'bewering dat iets niet zo is', ans2: 'ontvrienden op sociale media', ans3: 'niet meer herinneren', ans4: 'schamen voor je moeder', hintsemantic: 'nee',
    hintsentence: 'Hij ontkent dat hij heeft gespiekt.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'meewarig', ans1: 'met een beetje medelijden', ans2: 'groeiend', ans3: 'paars', ans4: 'meedenkend', hintsemantic: 'zielig',
    hintsentence: 'Toen ze die fout had gemaakt, keek hij haar meewarig aan.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'vergelijking', ans1: 'teams die tegen elkaar spelen', ans2: 'overtreffen van je buurman', ans3: 'beschouwing van overeenkomsten en verschillen', ans4: 'koopjes zoeken', hintsemantic: 'zoekplaatje',
    hintsentence: 'In vergelijking met de rest had hij een hoog cijfer.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'trachten', ans1: 'spelen', ans2: 'lezen', ans3: 'groeien', ans4: 'proberen', hintsemantic: 'poging',
    hintsentence: 'De docent trachtte woordenschatles leuker te maken.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'schrijfdoel', ans1: 'schrijver die rijk wil worden', ans2: 'doel dat de schrijver wil bereiken', ans3: 'toeschrijven naar einde van regel', ans4: 'punt achter zetten', hintsemantic: 'tekstdoel',
    hintsentence: 'Examens vragen vaak naar het schrijfdoel.', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'weerleggen', ans1: 'op de trap plaatsen', ans2: 'op de grond gooien', ans3: 'op het strand liggen', ans4: 'bewijzen dat iets niet juist is', hintsemantic: 'onwaar',
    hintsentence: 'De theorie wordt weerlegd door de feiten.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'bewijs(voering)', ans1: 'potpalm overplanten', ans2: 'literatuur zoeken', ans3: 'juistheid aantonen met feiten', ans4: 'zoeken naar bevestiging', hintsemantic: 'feitelijk',
    hintsentence: 'De jongen had geen bewijs voor zijn stelling.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'wildbreien', ans1: 'uitbreiden', ans2: 'breien van lapjes om de straat te versieren', ans3: 'met wilde bewegingen breien', ans4: 'knuffels van wilde beesten breien', hintsemantic: 'kleurrijk',
    hintsentence: 'Zijn tante ging bij het samenclubje om gezamenlijk te wildbreien.', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'citeren', ans1: 'stukje tekst letterlijk aanhalen', ans2: 'plagiaat plegen', ans3: 'loterij winnen', ans4: 'liedje zingen', hintsemantic: 'quote',
    hintsentence: 'Zijn vader citeert graag oude Grieken bij het avondeten.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'definitie', ans1: 'globale omschrijving van woord', ans2: 'vorm van verzet', ans3: 'nauwkeurige omschrijving van term', ans4: 'bizarre uitspraak', hintsemantic: 'begripsomschrijving',
    hintsentence: 'Hij keek in de encyclopedie om de definitie te vinden.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'expliciet', ans1: 'uitdrukkelijk', ans2: 'oprecht', ans3: 'niet openlijk', ans4: 'Spaans', hintsemantic: 'duidelijk zichtbaar',
    hintsentence: 'Hij gaf expliciet aan wat hij ervan vond.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'impliciet', ans1: 'uitdrukkelijk', ans2: 'oprecht', ans3: 'niet openlijk', ans4: 'Spaans', hintsemantic: 'verborgen',
    hintsentence: 'De rest moest maar raden, ze hield het impliciet.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'oorzaak', ans1: 'begin van een sprookje', ans2: 'map met tabbladen', ans3: 'gebeurtenis die aanzet tot schrijven', ans4: 'waarom iets zo is geworden', hintsemantic: 'begin',
    hintsentence: 'De oorzaak van het probleem was onbekend.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'aanleiding', ans1: 'begin van een sprookje', ans2: 'map met tabbladen', ans3: 'gebeurtenis die aanzet tot schrijven', ans4: 'waarom iets zo is geworden', hintsemantic: 'druppel',
    hintsentence: 'Die gebeurtenis vormde de aanleiding om te gaan schrijven.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'amper', ans1: 'lichtsterkte', ans2: 'behoorlijk', ans3: 'avontuurlijk', ans4: 'nauwelijks', hintsemantic: 'weinig',
    hintsentence: 'Ze begreep amper waarom ze er alweer uitgestuurd werd.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'constatering', ans1: 'verwijdering van etiket', ans2: 'aanzet', ans3: 'besmetting', ans4: 'vaststelling', hintsemantic: 'waarneming',
    hintsentence: 'Haar vader constateerde dat de kamer van zijn dochter nog steeds een puinhoop was.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'doelstelling', ans1: 'wat iemand wil bereiken', ans2: 'negeren van buitenspelregel', ans3: 'winderigheid', ans4: 'zoekplaatje', hintsemantic: 'ambitie',
    hintsentence: 'Zijn doel was om cum laude te slagen.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'juichpak', ans1: 'groep juichende mensen', ans2: 'pakje drinken tijdens pauze', ans3: 'wegwerken van stapel papier', ans4: 'oranje huispak voor WK voetbal', hintsemantic: 'stylist',
    hintsentence: 'De hele familie zat in juichpakken op de bank.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'middel', ans1: 'zeilbootje', ans2: 'manier om doel te bereiken', ans3: 'barbecuesaus', ans4: 'bureaulamp', hintsemantic: 'gereedschap',
    hintsentence: 'Welk middel heb je gebruikt om dat voor elkaar te krijgen?', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'nuanceren', ans1: 'hond aaien', ans2: 'lezer overtuigen', ans3: 'fijne onderscheidingen aanbrengen', ans4: 'stelling bewijzen', hintsemantic: 'verschil',
    hintsentence: 'Je moet niet zo negatief denken, het ligt genuanceerder.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'invalshoek', ans1: 'manier om een probleem te bekijken', ans2: 'wiskundige term', ans3: 'helling bij het struikelen', ans4: 'oplossing van een probleem', hintsemantic: 'perspectief',
    hintsentence: 'Vanuit welke invalshoek benader jij het?', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'heimelijk', ans1: 'stralend', ans2: 'stiekem', ans3: 'aandachtig', ans4: 'lichtgroen', hintsemantic: 'geheim',
    hintsentence: 'Hij was heimelijk verliefd op zijn klasgenoot.', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'reden', ans1: 'praatje', ans2: 'waarom iemand iets doet of vindt', ans3: 'onderbouwing van een standpunt', ans4: 'voordracht', hintsemantic: 'omdat',
    hintsentence: 'De reden voor zijn gedrag is onbekend.', hintimage: '', anscorrect: 2, level_id: 1 },
    { word: 'argument', ans1: 'praatje', ans2: 'waarom iemand iets doet of vindt', ans3: 'onderbouwing van een standpunt', ans4: 'voordracht', hintsemantic: 'deel betoog',
    hintsentence: 'Hij noemde ook argumenten die de tegenstander zou kunnen geven.', hintimage: '', anscorrect: 3, level_id: 1 },
    { word: 'elitair', ans1: 'aan de muur gehangen', ans2: 'vermoeiend', ans3: 'op het balkon geplaatst', ans4: 'niet voor de gewone man', hintsemantic: 'chic',
    hintsentence: 'Die besloten groep is erg elitair.', hintimage: '', anscorrect: 4, level_id: 1 },
    { word: 'gedijen', ans1: 'groeien', ans2: 'eten', ans3: 'opvoeden', ans4: 'zoeken', hintsemantic: 'plant',
    hintsentence: 'De muntplant gedijt goed in de volle zon.', hintimage: '', anscorrect: 1, level_id: 1 },
    { word: 'nurks', ans1: 'liefdevol', ans2: 'openlijk', ans3: 'knorrig', ans4: 'veelkleurig', hintsemantic: 'onaangenaam',
    hintsentence: 'Ik staar met een nurkse blik voor me uit.', hintimage: '', anscorrect: 3, level_id: 1 },
    ])

questionslevel2 = Question.create([
  { word: 'project X-feest', ans1: 'Sinterklaasfeest in Friesland', ans2: 'schoolgala', ans3: 'barbecue bij dertig graden', ans4: 'feest dat door sociale media uit de hand loopt', hintsemantic: 'Haren',
    hintsentence: 'Het project X-feest van de Harense Myrthe liep volledig uit de hand.', hintimage: '', anscorrect: 4,level_id: 2 },
    { word: 'aanbeveling', ans1: 'goede raad of advies', ans2: 'verwijt', ans3: 'aanvankelijke onwil', ans4: 'opschepperig gedrag', hintsemantic: 'recensie',
    hintsentence: 'Hij kocht dat product op aanbeveling van zijn vriend.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'beoordeling', ans1: 'slagingskans', ans2: 'positief of negatief oordeel over onderwerp', ans3: 'verduidelijking door meer details', ans4: 'intoetsen van pincode', hintsemantic: 'goedkeuring',
    hintsentence: 'Voor de knutselproject kreeg hij geen goede beoordeling.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'oplossing', ans1: 'verzadigingspunt', ans2: 'pasklaar maken', ans3: 'meting van tijd', ans4: 'antwoord op een probleem', hintsemantic: ' uitkomst',
    hintsentence: 'Een pasklare oplossing was er niet voorhanden.', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'paradox', ans1: 'weerbarstig', ans2: 'puberteit', ans3: 'schijnbare tegenstrijdigheid', ans4: 'schijnbare overeenstemming', hintsemantic: 'tegenspraak',
    hintsentence: 'Het is best paradoxaal dat je moet mislukken om te slagen.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'verklaring', ans1: 'meting van tijd', ans2: 'aanvankelijke onwil', ans3: 'uitleg waarom iets zo is', ans4: 'uitleg van een wiskundig probleem', hintsemantic: 'toelichting',
    hintsentence: 'Ze kon achteraf niet verklaren waarom ze die onvoldoende had gehaald.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'voorbeeld', ans1: 'concreet geval om te verduidelijken', ans2: 'voorkant van een standbeeld', ans3: 'boegbeeld op schip', ans4: 'bumper van auto', hintsemantic: 'plaatje',
    hintsentence: 'Ik ben op zoek naar een voorbeeldzin om dat woord mee te verduidelijken.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'louter', ans1: 'zuiver', ans2: 'heet', ans3: 'aandachtig', ans4: 'lovend', hintsemantic: 'puur',
    hintsentence: 'Nadat ze hun leugen hadden toegegeven, voelden ze zich gelouterd.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'oeverloze', ans1: 'aanlegpaal voor boot', ans2: 'brugwachtershokje', ans3: 'beperkte', ans4: 'zonder einde', hintsemantic: 'eeuwig',
    hintsentence: 'Ik moet steeds naar dat oeverloze gezeur luisteren!', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'drogreden', ans1: 'argument dat met water te maken heeft', ans2: 'verkeerd gebruikte argumentatie', ans3: 'ingedraaide gloeilamp', ans4: 'wankele glijbaan', hintsemantic: 'cirkelredenering',
    hintsentence: 'Vooral politici gebruiken veel drogredenen, blijkt uit onderzoek.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'smiespelen', ans1: 'gniffelen', ans2: 'groeten', ans3: 'opstaan', ans4: 'fluisteren', hintsemantic: 'geheim',
    hintsentence: 'Wat zitten die twee verdacht te smiespelen?', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'consistent', ans1: 'grappig', ans2: 'beschamend', ans3: 'logisch opgebouwd', ans4: 'bemoeiziek', hintsemantic: 'reeks',
    hintsentence: 'Zijn cijferopbouw is erg consistent.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'activeren', ans1: 'gegevens verstrekken', ans2: 'aansporen tot handelen', ans3: 'vermaken', ans4: 'laten inzien dat iets zo is', hintsemantic: 'energiek',
    hintsentence: 'Het doel van de schrijver is om zijn lezers te activeren.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'amuseren', ans1: 'gegevens verstrekken', ans2: 'aansporen tot handelen', ans3: 'vermaken', ans4: 'laten inzien dat iets zo is', hintsemantic: 'grappig',
    hintsentence: 'Het doel van de schrijver is om zijn lezers te amuseren.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'informeren', ans1: 'gegevens verstrekken', ans2: 'aansporen tot handelen', ans3: 'vermaken', ans4: 'laten inzien dat iets zo is', hintsemantic: 'kennis',
    hintsentence: 'Het doel van de schrijver is om zijn lezers te informeren.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'overtuigen', ans1: '', ans2: 'aansporen tot handelen', ans3: 'vermaken', ans4: 'laten inzien dat iets zo is', hintsemantic: 'overhalen',
    hintsentence: 'Het doel van de schrijver is om zijn lezers te overtuigen.', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'glamourwereld', ans1: 'wereld waarin alles mag', ans2: 'ideale wereld', ans3: 'wereld van schone schijn', ans4: 'wereld vol kakkerlakken', hintsemantic: 'voetbalvrouwen',
    hintsentence: 'Tijdschriften gaan meestal over de glamourwereld.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'consulteren', ans1: 'raadplegen', ans2: 'hoofdpijn bezorgen', ans3: 'snotneus krijgen', ans4: 'scriptie schrijven', hintsemantic: 'advies',
    hintsentence: 'Voor die gekke vlek kun je het beste een arts consulteren.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'egaliseren', ans1: 'braken', ans2: 'gelijkmaken', ans3: 'onvoldoende geven', ans4: 'salto springen', hintsemantic: 'vlak',
    hintsentence: 'De bouwers moesten eerst de grond egaliseren.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'militant', ans1: 'voorrang', ans2: 'strijdbaar', ans3: 'zelfverzekerd', ans4: 'veeleisend', hintsemantic: 'gevecht',
    hintsentence: 'De militante groepering kwam met zware eisen.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'moederbol', ans1: 'broodje gesmeerd door mama', ans2: 'hoofd van een moeder', ans3: 'territorium van moeders', ans4: 'zwangere buik', hintsemantic: 'bolwerk',
    hintsentence: 'Met mijn kind kom ik vaak terecht in een moederbol.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'beantwoording', ans1: 'ziektekiem', ans2: 'schoolkluisje', ans3: 'niet weten wat de docent bedoelt', ans4: 'antwoord op een gestelde vraag', hintsemantic: 'terugkoppeling',
    hintsentence: 'Ik zal jouw bericht zo snel mogelijk beantwoorden!', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'effect sorteren', ans1: 'op volgorde leggen', ans2: 'een ijsje eten', ans3: 'resultaat hebben', ans4: 'schapen aaien', hintsemantic: 'zichtbare invloed',
    hintsentence: 'Ik vraag me af of die maatregel effect zal sorteren.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'evenzeer', ans1: 'ook', ans2: 'echter', ans3: 'uitdrukkelijk', ans4: 'pijnlijk', hintsemantic: 'tevens',
    hintsentence: 'De regels gelden evenzeer voor jou als voor mij.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'kopje', ans1: 'dienblad', ans2: 'titel boven alinea(s)', ans3: 'krant waar het uit komt', ans4: 'aanrechtblad', hintsemantic: 'tekstscheiding',
    hintsentence: 'Volgens het kopje gaat het volgende deel over schaarste.', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'lotgevallen', ans1: 'struikeldraden', ans2: 'lotenverkoop', ans3: 'kattenspeeltjes', ans4: 'belevenissen', hintsemantic: 'meemaken',
    hintsentence: 'Opa vertelt altijd graag over zijn lotgevallen als kind.', hintimage: '', anscorrect: 4, level_id: 2 },
    { word: 'tegenwerping', ans1: 'reactie op eerdere bewering', ans2: 'teruggooien van bal', ans3: 'te vroeg inleveren', ans4: 'een aanzoek doen', hintsemantic: 'oneens',
    hintsentence: 'Als tegenwerping gaf zij aan dat het te tijdrovend zou zijn.', hintimage: '', anscorrect: 1, level_id: 2 },
    { word: 'toepassing', ans1: 'op maat maken', ans2: 'theorie schrijven over praktijk', ans3: 'in praktijk brengen van theorie', ans4: 'zoeken naar een antwoord', hintsemantic: 'gebruiken',
    hintsentence: 'Wij hebben die methode toegepast.', hintimage: '', anscorrect: 3, level_id: 2 },
    { word: 'verwijt', ans1: 'gevulde fruitschaal', ans2: 'beschuldigende afkeuring', ans3: 'toegepaste wiskunde', ans4: 'verbreding', hintsemantic: 'verkeerd',
    hintsentence: 'Mijn vrouw maakt mij voortdurend verwijten!', hintimage: '', anscorrect: 2, level_id: 2 },
    { word: 'olifantenpad', ans1: 'olifant op kikkerformaat', ans2: 'weg die dompteurs nemen', ans3: 'krukje waar olifant in circus op staat', ans4: 'kortere weg die iedereen neemt', hintsemantic: 'afsnijden',
    hintsentence: 'In het park was inmiddels een olifantenpad ontstaan.', hintimage: '', anscorrect: 4, level_id: 2 },
    ])

questionslevel3 = Question.create([
  { word: 'defenestreren', ans1: 'een glas breken', ans2: 'illegaal drinken', ans3: 'een aanzoek doen', ans4: 'uit het raam gooien', hintsemantic: 'venster',
    hintsentence: 'De docent defenestreerde de vervelende leerling', hintimage: '', anscorrect: 4,level_id: 3 },
    { word: 'impuls', ans1: 'oppepper', ans2: 'verzuim', ans3: 'peper toevoegen', ans4: 'lavalamp', hintsemantic: 'prikkel',
    hintsentence: 'Campagnes geven een forse impuls aan het bezoekersaantal.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'amputeren', ans1: 'verlangen naar vroeger', ans2: 'vernieuwen', ans3: 'afzetten', ans4: 'bevrijden van beperkingen of belemmeringen', hintsemantic: 'ledematen',
    hintsentence: 'Mijn been is tot de knie geamputeerd.', hintimage: '', anscorrect: 3, level_id: 3 },
    { word: 'relaas', ans1: 'lavalamp', ans2: 'verslag van iets wat je hebt meegemaakt', ans3: 'puberale woede', ans4: 'kritiek geven', hintsemantic: 'woordenstroom',
    hintsentence: 'Het was een relaas van een ongebruikelijk vertrek.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'ultieme', ans1: 'dringende', ans2: 'belangrijke', ans3: 'indrukwekkende', ans4: 'allerlaatste', hintsemantic: 'uiterste',
    hintsentence: 'Zij waagt nog een ultieme poging.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'urgente', ans1: 'dringende', ans2: 'belangrijke', ans3: 'indrukwekkende', ans4: 'allerlaatste', hintsemantic: 'geen tijd verliezen',
    hintsentence: 'Hij heeft een urgente boodschap voor de directeur.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'prominente', ans1: 'dringende', ans2: 'belangrijke', ans3: 'indrukwekkende', ans4: 'allerlaatste', hintsemantic: 'eerste plaats',
    hintsentence: 'Hij nodigde prominente gasten uit het bedrijfsleven uit.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'esthetische', ans1: 'of iets goed of slecht is', ans2: 'die met schoonheid te maken heeft', ans3: 'indrukwekkende', ans4: 'Griekse', hintsemantic: 'mooi',
    hintsentence: 'Esthetische tandheelkunde is voor mensen die ontevreden zijn met hun tanden.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'ethische', ans1: 'of iets goed of slecht is', ans2: 'die met schoonheid te maken heeft', ans3: 'indrukwekkende', ans4: 'Griekse', hintsemantic: 'braaf',
    hintsentence: 'Heeft zij wel integer en ethisch gehandeld?', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'significant', ans1: 'vierkant', ans2: 'glinsterend', ans3: 'uitdagend', ans4: 'veelbetekenend', hintsemantic: 'opvallend',
    hintsentence: 'Het onderzoek toonde geen significant verschil aan.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'egoglossy', ans1: 'persoonlijk eigendom', ans2: 'tijdschrift rond populair persoon', ans3: 'glimmende auto', ans4: 'eigen nagels lakken', hintsemantic: 'YOUP',
    hintsentence: 'Youp van t Hek was de zoveelste die kwam met een egoglossy.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'vergen', ans1: 'zoeken', ans2: 'opstaan voor de wekker', ans3: 'eisen', ans4: 'in herinnering brengen', hintsemantic: 'vragen',
    hintsentence: 'De inspanning heeft te veel van haar krachten gevergd.', hintimage: '', anscorrect: 3, level_id: 3 },
    { word: 'vermeende', ans1: 'echte', ans2: 'vindingrijke', ans3: 'waarvan men denkt dat hij ... is', ans4: 'knuffelende', hintsemantic: 'verdachte',
    hintsentence: 'De vermeende dader is opgepakt door de politie.', hintimage: '', anscorrect: 3, level_id: 3 },
    { word: 'memoreren', ans1: 'zoeken', ans2: 'opstaan voor de wekker', ans3: 'eisen', ans4: 'in herinnering brengen', hintsemantic: 'memory',
    hintsentence: 'In het voorafgaande is al gememoreerd dat hij altijd zijn eigen lunch meebracht.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'anderszins', ans1: 'echt', ans2: 'op een andere manier', ans3: 'vindingrijk', ans4: 'blijvend', hintsemantic: 'enerzins',
    hintsentence: 'Spijbelen of anderszins wordt hier streng bestraft.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'authentiek', ans1: 'echt', ans2: 'op een andere manier', ans3: 'vindingrijk', ans4: 'blijvend', hintsemantic: 'oorspronkelijk',
    hintsentence: 'Mijn vader bezit een authentieke Griekse vaas.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'permanent', ans1: 'echt', ans2: 'op een andere manier', ans3: 'vindingrijk', ans4: 'blijvend', hintsemantic: 'haarverf',
    hintsentence: 'Mijn vader heeft zijn haar gekleurd met permanente verf.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'inventief', ans1: 'echt', ans2: 'op een andere manier', ans3: 'vindingrijk', ans4: 'blijvend', hintsemantic: 'uitvinder',
    hintsentence: 'Als je weinig geld hebt, moet je inventief zijn.', hintimage: '', anscorrect: 3, level_id: 3 },
    { word: 'hypothese', ans1: 'inspanning', ans2: 'te bewijzen idee', ans3: 'toetsresultaat', ans4: 'aandacht', hintsemantic: 'vooronderstelling',
    hintsentence: 'De wetenschapper toetst zijn hypothese met een experiment.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'factor', ans1: 'kattenbak', ans2: 'medebepalend deel', ans3: 'verdachte', ans4: 'fabriek', hintsemantic: 'medeoorzaak',
    hintsentence: '', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'ontvrienden', ans1: 'verwijderen als vriend op sociale media', ans2: 'laten afhangen van', ans3: 'kleding maken', ans4: 'uitnodigen voor een feestje', hintsemantic: 'opschonen',
    hintsentence: 'De jongen heeft een kwart van zijn contacten ontvriend.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'latent', ans1: 'misselijk', ans2: 'plakkend', ans3: 'kauwend', ans4: 'verborgen', hintsemantic: 'sluimerend',
    hintsentence: 'Zijn verlangen is latent aanwezig.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'karikatuur', ans1: 'Oosterse vechtsport', ans2: 'belachelijke voorstelling van iets', ans3: 'opvallend verschijnsel', ans4: 'natuurgeweld', hintsemantic: 'portret',
    hintsentence: 'In de krant staan leuke karikaturen.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'fenomeen', ans1: 'Oosterse vechtsport', ans2: 'belachelijke voorstelling van iets', ans3: 'opvallend verschijnsel', ans4: 'natuurgeweld', hintsemantic: 'gebeurtenis',
    hintsentence: 'Wetenschappers kunnen het fenomeen niet verklaren.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'imponeren', ans1: 'optocht houden', ans2: 'twisten', ans3: 'provoceren', ans4: 'indruk maken', hintsemantic: 'stoer',
    hintsentence: 'De hoogspringer imponeerde de toeschouwers met zijn record.', hintimage: '', anscorrect: 4, level_id: 3 },
    { word: 'improviseren', ans1: 'ophangen', ans2: 'onvoorbereid uitvoeren', ans3: 'aanschaffen', ans4: 'indruk maken', hintsemantic: 'toneel',
    hintsentence: 'Jazzmuzikanten improviseren vaak in een solo.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'afweging', ans1: 'weging van voor- en nadelen', ans2: 'bespelen van instrument', ans3: 'bestellen van groente', ans4: 'op de weegschaal staan', hintsemantic: 'PMI-model',
    hintsentence: 'Een PMI-model kan helpen een goede afweging te maken.', hintimage: '', anscorrect: 1, level_id: 3 },
    { word: 'blijkens', ans1: 'vriendelijk', ans2: 'bang', ans3: 'zoals blijkt uit', ans4: 'schijnbaar', hintsemantic: 'volgens',
    hintsentence: 'Blijkens de handleiding moet je eerst de kap losmaken.', hintimage: '', anscorrect: 3, level_id: 3 },
    { word: 'beducht', ans1: 'vriendelijk', ans2: 'bang', ans3: 'zoals blijkt uit', ans4: 'schijnbaar', hintsemantic: 'op je hoede',
    hintsentence: 'De man is beducht voor de plannen van het kabinet.', hintimage: '', anscorrect: 2, level_id: 3 },
    { word: 'schoudersurfen', ans1: 'papegaai dragen op je schouder', ans2: 'ondersteboven op surfbord staan', ans3: 'meekijken terwijl iemand computert', ans4: 'water over je heen krijgen', hintsemantic: 'pottenkijker',
    hintsentence: 'Haar vader was zo bang dat ze iets verkeerds deed, dat hij constant aan het schoudersurfen was.', hintimage: '', anscorrect: 3, level_id: 3 }
    ])

questionslevel4 = Question.create([
  { word: 'boemerangkind', ans1: 'jongere die weer thuis komt wonen', ans2: 'kind dat speelt met boemerang', ans3: 'kind uit Australie', ans4: 'jongere die steeds in herhaling valt', hintsemantic: 'papa en mama',
    hintsentence: 'Toen ze klaar was met studeren werd ze een boemerangkind.', hintimage: '', anscorrect: 1,level_id: 4 },
    { word: 'dogma', ans1: 'verduistering', ans2: 'lavalamp', ans3: 'geloofsbeginsel', ans4: 'verkeerslicht', hintsemantic: 'geen discussie',
    hintsentence: 'Aan een dogma valt niets te veranderen.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'flatteus', ans1: 'met boeken vullend', ans2: 'er leuk uitziend', ans3: 'groen', ans4: 'winderig', hintsemantic: 'mooi',
    hintsentence: 'Als je dik en klein bent, staan korte jasjes en rokken niet zo flatteus.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'excessief', ans1: 'buitensporig', ans2: 'uniek', ans3: 'liefdevol', ans4: 'kritisch', hintsemantic: 'extreem',
    hintsentence: 'Bankiers krijgen excessieve bonussen.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'provocatie', ans1: 'voltijdstudie', ans2: 'potpalm', ans3: 'uitdaging', ans4: 'horlogemaker', hintsemantic: 'uitlokken',
    hintsentence: 'De puber provoceert zijn ouders graag.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'feminisering', ans1: 'negeren van buitenspelregel', ans2: 'sturen van kaartje', ans3: 'toenemen van de invloed van vrouwen', ans4: 'spelen van games', hintsemantic: 'meisjes',
    hintsentence: 'Volgens sommigen is de feminisering van het onderwijs een groot probleem.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'opsomming', ans1: 'bedoeling van de schrijver met de tekst', ans2: 'voornaamste kenmerken van verschijnsel', ans3: 'overdenking', ans4: 'reeks argumenten, verklaringen of voorbeelden', hintsemantic: 'veel',
    hintsentence: 'Maak een opsomming van alle voor- en nadelen.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'strekking', ans1: 'bedoeling van de schrijver met de tekst', ans2: 'voornaamste kenmerken van verschijnsel', ans3: 'overdenking', ans4: 'reeks argumenten, verklaringen of voorbeelden', hintsemantic: 'belangrijkste',
    hintsentence: 'De strekking van zijn verhaal was duidelijk.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'bespiegeling', ans1: 'bedoeling van de schrijver met de tekst', ans2: 'voornaamste kenmerken van verschijnsel', ans3: 'overdenking', ans4: 'reeks argumenten, verklaringen of voorbeelden', hintsemantic: 'nadenken',
    hintsentence: 'Hier een bespiegeling van de auteur.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'karakterisering', ans1: 'bedoeling van de schrijver met de tekst', ans2: 'voornaamste kenmerken van verschijnsel', ans3: '', ans4: 'reeks argumenten, verklaringen of voorbeelden', hintsemantic: 'hoofdpunten',
    hintsentence: 'Je kunt hem karakteriseren als een optimistische man.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'internetmeme', ans1: 'blaadje ter herinnering', ans2: 'hype die zich via internet verspreidt', ans3: 'digitaal prikbord', ans4: 'acteur op vacaturesite', hintsemantic: 'populair',
    hintsentence: 'Planking en owling zijn populaire internetmemes.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'arbitrair', ans1: 'in het beste geval', ans2: 'heel belangrijk', ans3: 'saai', ans4: 'willekeurig', hintsemantic: 'ongefundeerd',
    hintsentence: 'Volgens sommigen is er een teveel aan arbitraire regelingen.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'dimensies', ans1: 'zwarte gaten', ans2: 'televisieseries', ans3: 'lovende woorden', ans4: 'afmetingen', hintsemantic: 'grootte',
    hintsentence: 'De doos heeft drie dimensies: lengte, breedte en hoogte.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'idealiter', ans1: 'logisch', ans2: 'in het beste geval', ans3: 'met de toekomst te maken', ans4: 'inhoudsmaat', hintsemantic: 'ideaal',
    hintsentence: 'Idealiter komt hij volgende week uit het ziekenhuis naar huis.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'jegens', ans1: 'op jacht zijn', ans2: 'eveneens', ans3: 'ten opzichte van', ans4: 'afstandelijk', hintsemantic: 'tegenover',
    hintsentence: 'Je voelt wantrouwen jegens je tegenstander.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'omwille van', ans1: 'omdat het goed of nodig is', ans2: 'welwillend', ans3: 'met de wens om', ans4: 'van mening veranderen', hintsemantic: 'vanwege',
    hintsentence: 'Omwille van de veiligheid mag de politicus niet meer in het openbaar spreken.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'pril', ans1: 'heel belangrijk', ans2: 'omdat het goed of nodig is', ans3: 'gewoon', ans4: 'pas ontstaan', hintsemantic: 'jong',
    hintsentence: 'Hun relatie is nog erg pril.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'resistent', ans1: 'heel belangrijk', ans2: 'immuun', ans3: 'gewoon', ans4: 'pas ontstaan', hintsemantic: 'injectie',
    hintsentence: 'Hoe meer antibiotica je neemt, hoe meer resistente bacterien er zullen ontstaan.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'triviaal', ans1: 'heel belangrijk', ans2: 'omdat het goed of nodig is', ans3: 'gewoon', ans4: 'pas ontstaan', hintsemantic: 'normaal',
    hintsentence: 'Ik houd me niet bezig met triviale zaken.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'wezenlijk', ans1: 'heel belangrijk', ans2: 'omdat het goed of nodig is', ans3: 'gewoon', ans4: 'pas ontstaan', hintsemantic: 'behoorlijk',
    hintsentence: 'Dat detail maakt wel een wezenlijk verschil.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'lokwoning', ans1: 'doosje om mieren te lokken', ans2: 'muizenvallen in de keuken', ans3: 'huis voor werkloze kappers', ans4: 'huis om inbrekers te lokken en oppakken', hintsemantic: 'boeven',
    hintsentence: 'Maar enkele advocaten hebben bedenkingen bij de lokwoning.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'uitwerking', ans1: 'nadere uitleg in details of voorbeelden', ans2: 'schildersezel', ans3: 'rotsblok', ans4: 'tegenspreken wat eerder gezegd is', hintsemantic: 'verder',
    hintsentence: 'Het plan wordt nader uitgewerkt.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'stelling', ans1: 'feit of onderzoeksresultaat', ans2: 'ongefundeerde mening', ans3: 'mening die met argumenten wordt onderbouwd', ans4: 'retorische vraag', hintsemantic: 'standpunt',
    hintsentence: 'Ik ben het niet eens met de stelling.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'ontaarden', ans1: 'uitlopen op iets wat slechter is', ans2: 'aanhalen', ans3: 'aantasten', ans4: 'constateren', hintsemantic: 'uit de hand',
    hintsentence: 'Zuinigheid moet niet in gierigheid ontaarden.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'ondermijnen', ans1: 'uitlopen op iets wat slechter is', ans2: 'aanhalen', ans3: 'aantasten', ans4: 'constateren', hintsemantic: 'gezag',
    hintsentence: 'Deze grapjes ondermijnen het gezag van de directeur.', hintimage: '', anscorrect: 3, level_id: 4 },
    { word: 'onderkennen', ans1: 'uitlopen op iets wat slechter is', ans2: 'aanhalen', ans3: 'aantasten', ans4: 'constateren', hintsemantic: 'besef',
    hintsentence: 'Hij moet het risico tijdig onderkennen.', hintimage: '', anscorrect: 4, level_id: 4 },
    { word: 'arsenaal', ans1: 'verzameling', ans2: 'apenrots', ans3: 'kritische opmerking', ans4: 'te weinig aandacht', hintsemantic: 'grote hoeveelheid',
    hintsentence: 'Zij gebruikt een heel arsenaal aan sociale media.', hintimage: '', anscorrect: 1, level_id: 4 },
    { word: 'gestaag', ans1: 'zeilterm', ans2: 'onophoudelijk in een vast tempo', ans3: 'waxinelicht', ans4: 'overdreven', hintsemantic: 'voortdurend',
    hintsentence: 'Het werk vordert gestaag.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'ogenschijnlijk', ans1: 'afleidend', ans2: 'zoals het lijkt', ans3: 'openbaar', ans4: 'licht', hintsemantic: 'schijnbaar',
    hintsentence: 'Ogenschijnlijk gaat het allemaal vanzelf.', hintimage: '', anscorrect: 2, level_id: 4 },
    { word: 'recalcitrant', ans1: 'afgrijselijk', ans2: 'lezend', ans3: 'geneigd zich te verzetten', ans4: 'impulsief', hintsemantic: 'puberaal',
    hintsentence: 'De recalcitrante leerling werd uit de klas gestuurd.', hintimage: '', anscorrect: 3, level_id: 4 },
    ])  

questionslevel5 = Question.create([
  { word: 'rataplan', ans1: 'massa ongeordende dingen', ans2: 'looprad voor ratten', ans3: 'gemeen plannetje', ans4: 'tapdansterm', hintsemantic: 'troep',
    hintsentence: 'Zij komt morgen de hele rataplan ophalen.', hintimage: '', anscorrect: 1,level_id: 5 },
    { word: 'monumentale', ans1: 'indrukwekkende', ans2: 'eivormige', ans3: 'gerestaureerde', ans4: 'paarse', hintsemantic: 'groots',
    hintsentence: 'De leerling maakt een monumentale fout.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'nostalgie', ans1: 'verlangen naar feedback', ans2: 'verlangen naar vroeger', ans3: 'angst voor spinnen', ans4: 'angst voor lange woorden', hintsemantic: 'oma',
    hintsentence: 'Soms wordt ze geplaagd door nostalgische gevoelens.', hintimage: '', anscorrect: 2, level_id: 5 },
    { word: 'diversiteit', ans1: 'verkenning', ans2: 'nalatigheid', ans3: 'prototype', ans4: 'verscheidenheid', hintsemantic: 'variatie',
    hintsentence: 'Op de markt vind je een diversiteit aan producten.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'uniform', ans1: 'maatpak', ans2: 'moederbol', ans3: 'helemaal gelijk', ans4: 'totaal verschillend', hintsemantic: 'hetzelfde',
    hintsentence: 'Er zijn uniforme regels voor de brandveiligheid.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'weerzin', ans1: 'opnieuw enthousiast', ans2: 'laag pitje', ans3: 'hekel', ans4: 'paaskonijn', hintsemantic: 'onwil',
    hintsentence: 'Ik heb een grote weerzin tegen winkelen.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'begripsomschrijving', ans1: 'gevoel bij woord', ans2: 'globale omschrijving van probleem', ans3: 'juiste spelling', ans4: 'nauwkeurige omschrijving van term', hintsemantic: 'definitie',
    hintsentence: 'Voor de begripsomschrijving zocht hij in de encyclopedie.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'derhalve', ans1: 'daarom', ans2: 'ondanks dat', ans3: 'uitstekend', ans4: 'afgebrand', hintsemantic: 'omdat',
    hintsentence: 'Ik ben ziek en kan derhalve niet komen.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'eenduidig', ans1: 'winnaar bij darten', ans2: 'blijk gevend van onvermogen', ans3: 'onduidelijk', ans4: 'voor slechts een uitleg vatbaar', hintsemantic: 'duidelijk',
    hintsentence: 'Een eenduidige omschrijving kon de docent niet geven.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'gedogen', ans1: 'gebukt', ans2: 'toestaan', ans3: 'heerser in het oude Rome', ans4: 'afgesloten', hintsemantic: 'mag',
    hintsentence: 'Het is niet toegestaan, maar wordt gedoogd.', hintimage: '', anscorrect: 2, level_id: 5 },
    { word: 'breedparkeren', ans1: 'parkeren met een grote auto', ans2: 'parkeren op straat', ans3: 'twee parkeerplaatsen tegelijk bezet houden', ans4: 'de auto dwars in het vak zetten', hintsemantic: 'dubbel',
    hintsentence: 'Mannen beschuldigen vrouwen er vaak ten onrechte van dat ze breedparkeren.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'exploratie', ans1: 'nalatigheid', ans2: 'vorm van griep', ans3: 'verkenning', ans4: 'vaardigheid', hintsemantic: 'jungletocht',
    hintsentence: 'Hij is voortdurend probleemsituaties aan het exploreren.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'nihil', ans1: 'niets', ans2: 'weinig', ans3: 'veel', ans4: 'alles', hintsemantic: '-',
    hintsentence: 'De praktische resultaten van het project waren nihil.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'evalueren', ans1: 'onderzoeken wat goed en slecht aan iets is', ans2: 'de blijde boodschap brengen', ans3: 'naar een hogere functie gaan', ans4: 'groeien', hintsemantic: 'rapport',
    hintsentence: 'De manager evalueert alternatieve plannen en projecten.', hintimage: '', anscorrect: 1,level_id: 5 },
    { word: 'expanderen', ans1: 'onderzoeken wat goed en slecht aan iets is', ans2: 'de blijde boodschap brengen', ans3: 'naar een hogere functie gaan', ans4: 'groeien', hintsemantic: 'groter',
    hintsentence: 'Ons bedrijf opent nieuwe vestigingen en expandeert naar het buitenland.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'exponentiele', ans1: 'afgrijselijk', ans2: 'aandachtig', ans3: 'gelukkig lijkend', ans4: 'zeer snel stijgend', hintsemantic: 'groter',
    hintsentence: 'Een voorbeeld van exponentiele afname is radioactief verval.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'inzake', ans1: 'overbodige', ans2: 'betreffende', ans3: 'oostelijke', ans4: 'ondanks de genoemde bezwaren', hintsemantic: 'over',
    hintsentence: 'Wat is jouw mening over het verdrag inzake de rechten van het kind?', hintimage: '', anscorrect: 2, level_id: 5 },
    { word: 'gevoelswaarde', ans1: 'verlangen naar vroeger', ans2: 'de waarde van emoties', ans3: 'mening of gevoel van de schrijver', ans4: 'prijs van een dagboek', hintsemantic: 'betrokken',
    hintsentence: 'Gevoelswaarde is totaal anders dan werkelijke waarde.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'retorische vraag', ans1: 'bewering in vraagvorm', ans2: 'vraag met meerdere antwoorden', ans3: 'domme vraag', ans4: 'vraag voor docent', hintsemantic: 'eens',
    hintsentence: 'Een betoog kun je goed beginnen met een retorische vraag.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'toelichting', ans1: 'oplichten van een toeschouwer', ans2: 'gemaakte begroting', ans3: 'voorbeelden of meer uitleg', ans4: 'lamp op voorwerp richten', hintsemantic: 'toevoeging',
    hintsentence: 'De docent lichtte de geschreven feedback nog mondeling toe.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'vettaks', ans1: 'nuancering', ans2: 'pleidooi', ans3: 'belasting op vetrijke voeding', ans4: 'boete bij gebruik van stopwoordjes', hintsemantic: 'chips',
    hintsentence: 'De partij stelde voor een vettaks te introduceren in Nederland.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'handzaam', ans1: 'knap', ans2: 'handig', ans3: 'blijkbaar', ans4: 'mooi', hintsemantic: 'makkelijk',
    hintsentence: 'Tabloid is een veel handzamer formaat voor een krant.', hintimage: '', anscorrect: 2, level_id: 5 },
    { word: 'subargument', ans1: 'voorbarig oordeel of standpunt', ans2: 'iets wat niet mag', ans3: 'voorspelling', ans4: 'ondergeschikt argument', hintsemantic: 'ondersteuning',
    hintsentence: 'Het argument werd weer ondersteund voor een subargument.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'vooroordeel', ans1: 'voorbarig oordeel of standpunt', ans2: 'iets wat niet mag', ans3: 'voorspelling', ans4: 'ondergeschikt argument', hintsemantic: 'oppervlakkig',
    hintsentence: 'Dat mannen vaker vreemdgaan dan vrouwen is een hardnekkig vooroordeel.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'taboe', ans1: 'voorbarig oordeel of standpunt', ans2: 'iets wat niet mag', ans3: 'voorspelling', ans4: 'ondergeschikt argument', hintsemantic: 'verboden',
    hintsentence: 'Helaas rust in sommige landen nog een taboe op homoseksualiteit.', hintimage: '', anscorrect: 2, level_id: 5 },
    { word: 'prognose', ans1: 'voorbarig oordeel of standpunt', ans2: 'iets wat niet mag', ans3: 'voorspelling', ans4: 'ondergeschikt argument', hintsemantic: 'vooruitzicht',
    hintsentence: 'De prognose is niet erg gunstig.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'begiftigd', ans1: 'toedienen van schadelijke stof', ans2: 'bestrijden van ongedierte', ans3: 'met behulp van', ans4: 'in het bezit van', hintsemantic: 'talent',
    hintsentence: 'Hij is begiftigd met unieke talenten.', hintimage: '', anscorrect: 4, level_id: 5 },
    { word: 'evident', ans1: 'heel duidelijk', ans2: 'paraat', ans3: 'zeilend', ans4: 'turnend', hintsemantic: 'logisch',
    hintsentence: 'Er is een evidente vergissing gemaakt.', hintimage: '', anscorrect: 1, level_id: 5 },
    { word: 'kentering', ans1: 'kapen van een schip', ans2: 'verschil aanduiden', ans3: 'verandering', ans4: 'kerstbal ophangen', hintsemantic: 'koerswijziging',
    hintsentence: 'Er is een positieve kentering te zien.', hintimage: '', anscorrect: 3, level_id: 5 },
    { word: 'socialbesitas', ans1: 'verlangen naar aandacht', ans2: 'zoektocht naar roem', ans3: 'altijd goede antwoorden geven', ans4: 'dwangmatig en overmatig gebruik van sociale media', hintsemantic: 'netwerk',
    hintsentence: 'Toenemend internetgebruik en socialbesitas gaan hand in hand.', hintimage: '', anscorrect: 4, level_id: 5 },
    ])

questionslevel6 = Question.create([
  { word: 'beurtbalkje', ans1: 'volgorde van turntoestellen', ans2: 'scheidingsblokje voor boodschappen', ans3: 'nummertje dat je beurt aangeeft', ans4: 'zwart balkje voor ogen van verdachte', hintsemantic: 'supermarkt',
    hintsentence: 'Hij ergert zich aan mensen die hun beurtbalkje niet achter hun boodschappen leggen.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'ambivalent', ans1: 'zelfverzekerd', ans2: 'veeleisend', ans3: 'gestippeld', ans4: 'tweeslachtig', hintsemantic: 'dubbel',
    hintsentence: 'De docenten staan ambivalent tegenover de nieuwe plannen.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'intrinsiek', ans1: 'innerlijk', ans2: 'luisterend', ans3: 'zoekend', ans4: 'zwaar', hintsemantic: 'binnen',
    hintsentence: 'De leerling heeft een intrinksieke motivatie om goed te presteren.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'perceptie', ans1: 'teleurstelling', ans2: 'waarneming', ans3: 'groetje', ans4: 'deelbaar door honderd', hintsemantic: 'blik',
    hintsentence: 'Wat u nu vertelt is niet mijn perceptie van wat er gebeurd is.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'preventie', ans1: 'maatregel na gebeurtenis', ans2: 'verlangen naar vroeger', ans3: 'maatregel om iets vervelends te voorkomen', ans4: 'stilstaan van horloge', hintsemantic: 'tevoren',
    hintsentence: 'Op het gebied van gezondheid zou de overheid veel meer aan preventie kunnen doen.', hintimage: '', anscorrect: 3, level_id: 6 },
    { word: 'steevast', ans1: 'richting', ans2: 'bijzonder', ans3: 'zonnebril', ans4: 'iedere keer weer', hintsemantic: 'constant',
    hintsentence: 'Die instelling houdt steevast na de zomervakantie open huis.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'voorbarig', ans1: 'richting', ans2: 'te vroeg', ans3: 'inzake', ans4: 'bijzonder', hintsemantic: 'te snel',
    hintsentence: 'De kranten waren in hun commentaar al te voorbarig.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'vergaren', ans1: 'bijeenkomst van de leiding', ans2: 'verzamelen', ans3: 'heel hard lachen', ans4: 'oprollen', hintsemantic: 'samenbrengen',
    hintsentence: 'Hij heeft een fortuin vergaard.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'teloorgang', ans1: 'ondergang', ans2: 'nooduitgang', ans3: 'hellend vlak', ans4: 'vals plat', hintsemantic: 'neerwaarts',
    hintsentence: 'Na het vertrek van de voetballer werd de teloorgang van de club langzaam ingezet.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'innovatie', ans1: '', ans2: '', ans3: '', ans4: 'vernieuwing', hintsemantic: '',
    hintsentence: 'Innovatie wordt belangrijk gevonden voor de economie.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'gameboyrug', ans1: 'kromgebogen rug van een gamer', ans2: 'rug in de vorm van gameboy', ans3: 'spelende jongen', ans4: 'voor veel geld verkochte gameboy', hintsemantic: 'scheef',
    hintsentence: 'De gymleraar herkende bij de leerling een gameboyrug.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'fungeren', ans1: 'schimmel kweken', ans2: 'dienst doen als', ans3: 'voorkomen', ans4: 'imiteren', hintsemantic: 'gebruik',
    hintsentence: 'Bij de plechtigheid fungeerde hij als ceremoniemeester.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'cruciaal', ans1: 'pijnlijk', ans2: 'moeizaam', ans3: 'gevoelsmatig', ans4: 'doorslaggevend', hintsemantic: 'belangrijk',
    hintsentence: 'Creativiteit is cruciaal voor vernieuwing.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'bejegenen', ans1: 'bezet houden', ans2: 'zich afvragen', ans3: 'omgaan met', ans4: 'dienstdoen als', hintsemantic: 'houding',
    hintsentence: 'Hij bejegent iedereen bot.', hintimage: '', anscorrect: 3, level_id: 6 },
    { word: 'hierarchie', ans1: 'rangorde', ans2: 'oude spullen opgraven', ans3: 'identiteitsbewijs', ans4: 'rij boeken', hintsemantic: 'trap',
    hintsentence: 'In ieder bedrijf is een hierarchie, ook als de mensen zich als gelijkwaardig gedragen.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'offensief', ans1: 'op de tenen', ans2: 'cirkelend', ans3: 'verdedigend', ans4: 'aanvallend', hintsemantic: 'defensief',
    hintsentence: 'Zij voetbalde erg offensief.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'associeren', ans1: 'in verband brengen met', ans2: 'aardbei plukken', ans3: 'omgaan met', ans4: 'gebruiken', hintsemantic: 'eerste gedachte',
    hintsentence: 'Ik associeer muizen direct met kaas.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'appelleren', ans1: 'gebruiken', ans2: 'aantonen', ans3: 'een beroep doen op', ans4: 'appel eten', hintsemantic: 'omgaan met',
    hintsentence: 'Die school geeft onderwijs dat appelleert aan de belevingswereld van de leerling.', hintimage: '', anscorrect: 3, level_id: 6 },
    { word: 'uitwijzen', ans1: 'gebruiken', ans2: 'aantonen', ans3: 'afzwakken', ans4: 'omgaan met', hintsemantic: 'blijkt',
    hintsentence: 'De toekomst zakt het uitwijzen.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'relativeren', ans1: 'gebruiken', ans2: 'opschrijven', ans3: 'afzwakken', ans4: 'omgaan met', hintsemantic: 'minder',
    hintsentence: 'Je kunt niet alles relativeren, er zijn ook de echt grote dingen waar het om gaat.', hintimage: '', anscorrect: 3, level_id: 6 },
    { word: 'tuigdorp', ans1: 'dorp aan rand van stad', ans2: 'dorp binnen stad', ans3: 'dorp buiten Randstad', ans4: 'afgelegen locatie als woonplaats voor criminelen', hintsemantic: 'boef',
    hintsentence: 'Zijn toehoorder trok een wenkbrauw op toen hij hoorde over de plannen voor het tuigdorp.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'repressieve', ans1: 'zonder verzet', ans2: 'onderdrukkend', ans3: 'uitgaand van mogelijkheden die er zijn', ans4: 'veranderlijk', hintsemantic: 'neerwaarts',
    hintsentence: 'De voorgestelde maatregelen zijn erg repressief.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'dynamisch', ans1: 'zonder verzet', ans2: 'onderdrukkend', ans3: 'uitgaand van mogelijkheden die er zijn', ans4: 'veranderlijk', hintsemantic: 'beweeglijk',
    hintsentence: 'Er is sprake van dynamische ontwikkelingen in de financiele wereld.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'pragmatisch', ans1: 'zonder verzet', ans2: 'onderdrukkend', ans3: 'uitgaand van mogelijkheden die er zijn', ans4: 'veranderlijk', hintsemantic: 'praktisch',
    hintsentence: 'Het fileprobleem wordt pragmatisch benaderd.', hintimage: '', anscorrect: 3, level_id: 6 },
    { word: 'lijdzaam', ans1: 'zonder verzet', ans2: 'onderdrukkend', ans3: 'uitgaand van mogelijkheden die er zijn', ans4: 'veranderlijk', hintsemantic: 'gelaten',
    hintsentence: 'Ik moest lijdzaam toezien dat mijn zusje weer werd voorgetrokken.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'conclusie', ans1: 'gevoel van de schrijver', ans2: 'gevolgtrekking', ans3: 'betoog', ans4: 'korte weergave van het belangrijkste', hintsemantic: 'dus',
    hintsentence: 'Ik kom tot de conclusie dat ons plan niet goed is.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'samenvatting', ans1: 'gevoel van de schrijver', ans2: 'gevolgtrekking', ans3: 'betoog', ans4: 'korte weergave van het belangrijkste', hintsemantic: 'kortom',
    hintsentence: 'Van veel romans is op internet een samenvatting te vinden.', hintimage: '', anscorrect: 4, level_id: 6 },
    { word: 'niet aflatend', ans1: 'steeds volhoudend', ans2: 'intens', ans3: 'oorspronkelijk', ans4: 'vergevorderd', hintsemantic: 'constant',
    hintsentence: 'Zij was hem niet aflatend aan het plagen.', hintimage: '', anscorrect: 1, level_id: 6 },
    { word: 'verloedering', ans1: 'gesp van riem', ans2: 'achteruitgang', ans3: 'korte notitie', ans4: 'leenwoord uit het Frans', hintsemantic: 'slechter',
    hintsentence: 'De wijk verloedert als de huizen niet snel worden opgeknapt.', hintimage: '', anscorrect: 2, level_id: 6 },
    { word: 'epibreren', ans1: 'rillen van de kou', ans2: 'vullen van fruitschaal', ans3: 'iemand onderbreken', ans4: 'doen alsof je met iets belangrijks bezig bent', hintsemantic: 'klas',
    hintsentence: 'Na zus jaar vwo beheerste hij vooral de kunst van het epibreren.', hintimage: '', anscorrect: 4, level_id: 6 },
    ])

DeadlineMedal.create([
    { name: 'Deadline level 1', description: 'Speel level 1 voor de sluitingsdatum', xp: 1000, level_number: 1 },
    { name: 'Deadline level 2', description: 'Speel level 2 voor de sluitingsdatum', xp: 1000, level_number: 2 },
    { name: 'Deadline level 3', description: 'Speel level 3 voor de sluitingsdatum', xp: 1000, level_number: 3 },
    { name: 'Deadline level 4', description: 'Speel level 4 voor de sluitingsdatum', xp: 1000, level_number: 4 },
    { name: 'Deadline level 5', description: 'Speel level 5 voor de sluitingsdatum', xp: 1000, level_number: 5 },
    { name: 'Deadline level 6', description: 'Speel level 6 voor de sluitingsdatum', xp: 1000, level_number: 6 },
    ])

NoHintsMedal.create([
    { name: 'Geen hints level 1', description: 'Geen hints gebruikt in level 1', xp: 1000, level_number: 1 },
    { name: 'Geen hints level 2', description: 'Geen hints gebruikt in level 2', xp: 1000, level_number: 2 },
    { name: 'Geen hints level 3', description: 'Geen hints gebruikt in level 3', xp: 1000, level_number: 3 },
    { name: 'Geen hints level 4', description: 'Geen hints gebruikt in level 4', xp: 1000, level_number: 4 },
    { name: 'Geen hints level 5', description: 'Geen hints gebruikt in level 5', xp: 1000, level_number: 5 },
    { name: 'Geen hints level 6', description: 'Geen hints gebruikt in level 6', xp: 1000, level_number: 6 },
    ])

ThreeStarMedal.create([
    { name: '3 Sterren level 1', description: 'Haal drie sterren in level 1', xp: 1000, level_number: 1 },
    { name: '3 Sterren level 2', description: 'Haal drie sterren in level 2', xp: 1000, level_number: 2 },
    { name: '3 Sterren level 3', description: 'Haal drie sterren in level 3', xp: 1000, level_number: 3 },
    { name: '3 Sterren level 4', description: 'Haal drie sterren in level 4', xp: 1000, level_number: 4 },
    { name: '3 Sterren level 5', description: 'Haal drie sterren in level 5', xp: 1000, level_number: 5 },
    { name: '3 Sterren level 6', description: 'Haal drie sterren in level 6', xp: 1000, level_number: 6 },
    ])

TwentyFiveInRowMedal.create([
    { name: '25 Vragen achter elkaar goed', description: 'Beantwoord 25 vragen achter elkaar correct', xp: 1000 }
    ])

FiftyInRowMedal.create([
    { name: '50 Vragen achter elkaar goed', description: 'Beantwoord 50 vragen achter elkaar correct', xp: 1000 }
    ])

HundredInRowMedal.create([
    { name: '100 Vragen achter elkaar goed', description: 'Beantwoord 100 vragen achter elkaar correct', xp: 1000}
    ])
HundredMedal.create([
    { name: '100 Vragen goed', description: 'Beantwoord 100 vragen correct', xp: 1000 }
    ])
ThousandMedal.create([
    { name: '1000 Vragen Goed', description: 'Beantwoord 1000 vragen correct', xp: 1000  }
    ])
AllMedalsMedal.create([
    { name: 'Alle trofeeen behaald', description: 'Haal alle trofeeen', xp: 1000,  }
    ])